USE Test

--Pho diem Toan
SELECT Toan, COUNT(STT)
FROM DSHN
WHERE Toan IS NOT NULL
GROUP BY Toan
Order by Toan 

--Trung Binh 7
SELECT AVG(Toan)  
FROM DSHN

--Trung vi 5.3

--Phuong sai 5.21
CREATE TABLE #Temp2(Diem float)
INSERT INTO #Temp2
SELECT POWER(Toan-AVG(Toan), 2)
FROM DSHN
GROUP BY Toan

SELECT SUM(Diem)/(COUNT (Diem)-1) 
FROM #Temp2

--Do lech chuan 2.28
SELECT SQRT(SUM(Diem)/(COUNT (Diem)-1)) 
FROM #Temp2

--Mode 8.4
SELECT TOP 1 Toan
FROM DSHN
WHERE Toan IS NOT NULL
GROUP BY Toan
Order by COUNT(STT) DESC

--Pho diem Van
SELECT Nguvan, COUNT(STT)
FROM DSHN
WHERE Nguvan IS NOT NULL
GROUP BY Nguvan
Order by Nguvan

--Pho diem Ngoai ngu
SELECT Ngoaingu, COUNT(STT)
FROM DSHN
WHERE Ngoaingu IS NOT NULL
GROUP BY Ngoaingu
Order by Ngoaingu

--Pho diem KHXH
SELECT KHXH, COUNT(STT)
FROM DSHN
WHERE KHXH IS NOT NULL
GROUP BY KHXH
Order by KHXH

--Pho diem KHTN
SELECT KHTN, COUNT(STT)
FROM DSHN
WHERE KHTN IS NOT NULL
GROUP BY KHTN
Order by KHTN